#pragma once

static const unsigned int n_vars = 353;
enum var :int {
	cityDensity = 0,
	urban = 1,
	countryDensity = 2,
	familyType = 3,
	familySingleMale = 8,
	familySingleFemale = 15,
	familyCoupleOnly = 21,
	familyUnder20 = 27,
	nChildren = 29,
	AvgSiblingDistance = 30,
	AvgCoupleDistance = 32,
	AvgAgeFirstChild = 34,
	AverageHouseHoldExtended = 36,
	AvgHousehold = 37,
	ComorbidityRate = 38,
	HospBedsDensity = 98,
	ICUBedsDensity = 99,
	NurseProportion = 100,
	MDProportion = 101,
	contaminationRisk = 102,
	prSymptomatic = 103,
	delaySymptomatic = 104,
	prCritical = 106,
	prSevereAgeTh = 108,
	prDiagnosed = 110,
	delayDiagnosis = 111,
	delayHospitalized = 113,
	PrDeath = 115,
	delayICUDeath = 116,
	delayRecovery = 118,
	PCRSensitivity = 120,
	schoolClassSize = 121,
	ProportionsmallCompanies = 122,
	avgEmployeNumber = 123,
	employmentRate = 124,
	nShopping = 125,
	AvgShoppingEncounters = 126,
	AvgShoppingFreq = 127,
	AvgTripPerWorkDay = 128,
	AvgTripGoingOutFreq = 129,
	AvgTransportEncounters = 130,
	AvgTransportEncountersLow = 131,
	AvgFriends = 132,
	AvgFriendEncountersFreq = 133,
	AvgFriendperEncounters = 134,
	AvgEventsPerIndividualPerWeek = 135,
	AvgEventPersons = 136,
	AvgInternationalContaminated = 137,
	AvgDelaiInternational = 138,
	prAsymp = 139,
	prSuccessTrack = 141,
	AvgTrackingTim = 142,
	Phase3Threshold = 143,
	ContainementThreshold = 144,
	prSevere = 145,
	socialDistancing = 148,
	prMortMale = 149,
	prMortFemale = 249,
	il9 = 349,
	serologySe = 350,
	serologyCapacity = 352,

};

static const int nLinks = 13;

enum typeOfLink : int {
	lGoingOutTransport = 0, 
	lEvent = 1,
	lFriend = 2,
	lIntercity = 3,
	lIntrafamilialHousehold = 5,
	lIntrafamilialExterior = 6,
	lShooping = 7,
	lTransport = 8,
	lWork = 9,
	lSchool = 10,
	lForeign = 11,
	lWorkTransport = 12
};

const static int max_days = 360;